version: "3.9"

services:
  whatsapp-ai-bot:
    container_name: whatsapp-ai-bot
    image: registry.gitlab.com/nakul-gupta/whatsapp-ai-bot:latest

    ports:
      - "3003:3003"

    env_file:
      - .env

    restart: unless-stopped

    volumes:
      - logs_data:/app/logs
      - /var/www/whatsapp-ai-bot/apps/dashboard:/app/apps/dashboard
      - dashboard_sync:/app/apps/dashboard # This handles the auto-copy

volumes:
  logs_data:
  dashboard_sync:
    driver: local
    driver_opts:
      type: none
      device: /var/www/whatsapp-ai-bot/apps/dashboard
      o: bind